version: '3.8'

services:
  # We will define our FastAPI backend here
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development

  # We will define our Streamlit frontend here
  frontend:
    build:
      context: ./frontend
    ports:
      - "8502:8502"
    depends_on:
      - backend

  # Later, we will add MLflow and Prometheus here
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.10.2
    container_name: mlflow_server
    ports:
      - "5001:5000"
    command: mlflow server --host 0.0.0.0 --port 5000

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

